[package]
name = "typetag"
version = "0.2.3"
authors = ["David Tolnay <dtolnay@gmail.com>"]
categories = ["encoding", "no-std"]
description = "Serde serializable and deserializable trait objects"
documentation = "https://docs.rs/typetag"
edition = "2018"
keywords = ["serde", "serialization"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/dtolnay/typetag"
rust-version = "1.62"

[workspace]
members = ["impl", "macro"]

[dependencies]
erased-serde = { version = "0.3", default-features = false, features = ["alloc"] }
inventory = "0.3"
once_cell = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
typetag-macro = { version = "=0.2.3", path = "macro" }

[dev-dependencies]
bincode = "1.0"
serde_json = "1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
