[package]
name = "typetag-macro"
version = "0.2.3"
authors = ["David Tolnay <dtolnay@gmail.com>"]
description = "Implementation detail of the typetag crate"
documentation = "https://docs.rs/typetag"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dtolnay/typetag"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
typetag-impl = { version = "=0.2.3", path = "../impl" }


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
